[
 {
   "ques": "<strong>Can I use the music for free?</strong>",
   "ans": "<!-- wp:paragraph -->\nYes, provided all the following conditions are met:\n<!-- /wp:paragraph -->\n\n<!-- wp:list -->\n<ul><li>You are an<strong> independent creator</strong></li><li>You use the content on social media/digital platforms incl.<strong> Facebook, Twitter, Instagram &amp; YouTube or blog/website.</strong></li><li>You give proper <strong>credit</strong> as mentioned <a href=\"https://www.elshawn.com/Usage-Policy/Social-Media-use\">here</a>.</li></ul>\n<!-- /wp:list -->"
 },
 {
   "ques": "<strong>How do I credit?</strong>",
   "ans": "You have to provide credit according to the platform where you are using the music. This is described on this <a href=\"https://www.elshawn.com/Usage-Policy/Social-Media-use\">link</a>"
 },
 {
   "ques": "<strong>What if I don't want to credit? </strong>\n",
   "ans": "You need to purchase a <a href=\"https://www.elshawn.com/Usage-Policy/commercial-license\">commercial license</a>. Thereafter, you may use music without giving credit."
 },
 {
   "ques": "<strong>What is UGC by independent creator?</strong>\n",
   "ans": "Any individual or group of individuals who are using the music to support their videos in content generated by them. Examples of this include, you reviewing a product sharing opinions (incl unboxing etc.) or gaming screencast, DIY videos, etc. Any commercial usage (such as digital advertisement or TVC) requires a <a href=\"https://www.elshawn.com/Usage-Policy/commercial-license\">commercial license</a>."
 },
 {
   "ques": "<strong>Can I use this in independent games?</strong>\n",
   "ans": "No, that is considered under commercial activity hence you need a <a href=\"https://www.elshawn.com/Usage-Policy/commercial-license\">commercial license</a>. "
 },
 {
   "ques": "<strong>Can I remix?</strong>\n",
   "ans": "Not right away but you may contact me using this <a href=\"https://www.elshawn.com/contact\">form</a>."
 },
 {
   "ques": "<strong>Can I use this commercially?</strong>\n",
   "ans": "Yes but with a <a href=\"https://www.elshawn.com/Usage-Policy/commercial-license\">commercial license</a>. "
 },
 {
   "ques": "<strong>Are these songs copyrighted?</strong>\n",
   "ans": "Yes\n"
 },
 {
   "ques": "<strong>Can I download for free?</strong>\n",
   "ans": "Yes. You can download for free for personal usage.\n"
 },
 {
   "ques": "<strong>Can I use commercially if I paid to download (from iTunes etc.)</strong>\n",
   "ans": "No, that is also for personal usage only. I highly appreciate you buying from itunes as that supports my music work.\n"
 },
 {
   "ques": "<strong>What social networks can I use your music/tracks?</strong>\n",
   "ans": "<!-- wp:paragraph -->\nThe following:\n<!-- /wp:paragraph -->\n\n<!-- wp:list -->\n<ul><li>Facebook</li><li>Twitter</li><li>Instagram</li><li>YouTube</li><li>Your website or blog</li></ul>\n<!-- /wp:list -->"
 },
 {
   "ques": "<strong>Can I monetize YT videos?</strong>\n",
   "ans": "Yes.\n"
 },
 {
   "ques": "<strong>I received a claim on YouTube, what do I do?</strong>\n",
   "ans": "Please <a href=\"https://www.elshawn.com/contact\">contact me</a>, I'll look into it. \n"
 },
 {
   "ques": "<strong>Can I use your music for sampling?</strong>\n",
   "ans": "Not right away, but please <a href=\"https://www.elshawn.com/contact\">contact me</a> for such questions.\n"
 },
 {
   "ques": "<strong>Is there any other restriction on your music usage?</strong>\n",
   "ans": "As long as you agree with the terms, there shouldn't be any problem although if your content consists of the following, you can not use my music:\n<ul><li>Hate Speech</li><li>Disturbing / Offensive content</li><li>Illegal content</li><li>Sexually themed content</li></ul>"
 },
 {
   "ques": "<strong>Can I make money from your music?</strong>\n",
   "ans": "You can monetize on YouTube if you are an independent creator provided you follow the terms. Of course the commercial license enables you to monetize using my music.\n"
 },
 {
   "ques": "<strong>Can I upload your music to Spotify (or other streaming platform) under my name?</strong>\n",
   "ans": "No. You can't even upload under my name. \n"
 },
 {
   "ques": "<strong>I am an independent YT based label and I want to feature your music on the channel, what to do?</strong>\n",
   "ans": "Please contact me using this <a href=\"https://www.elshawn.com/contact\">form</a>.\n"
 },
 {
   "ques": "<strong>I have a commercial license, what are the dos and don'ts?</strong>\n",
   "ans": "You can use my music without giving credits as well as for any commercial purpose except if your content includes the following:\n<ul><li>Hate Speech</li><li>Disturbing / Offensive content</li><li>Illegal content</li><li>Sexually themed content</li></ul>\n"
 }
]